name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/checkout@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        # updating pip
        python -m pip install --upgrade pip
        # flake8 and its plugins installation
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # dependencies installation
        pip install -r requirements.txt
    - name: Test with flake8 and django tests
      run: |
        # flake8 check launch
        python -m flake8